Refactor OpenAPI optional path parameters detection to use lists instead of a trie
google/grr pull request #841
Opened 2020-09-07 16:23 UTC by alexandrucosminmihai

## Introduction
In [PR 837](https://github.com/google/grr/pull/837) I introduced the code that detects optional path parameters from the GRR API routes and describes them accordingly in the generated OpenAPI description. That implementation was based on a trie in order to represent the routes. In this PR I introduce an alternative solution that replaces the trie with lists, improving readability, but affecting the time complexity.

## How it works
The core idea is the same as in the trie-based solution: we want to find and group routes that have a common "stem" route and continue to extend it with **consecutive terminal path parameters** (e.g. `_prefix_/arg1`, `_prefix_/arg1/arg2` and `_prefix_/arg1/arg2/arg3` can be reduced to `_prefix_/arg1/arg2/arg3` with `required_args = [arg1]` and `optional_args = [arg2, arg3]`). The path parameters that are present in the stem route will be required in the final (longest) route of the detected group, while the rest of the path parameters (the ones that are not in the stem) will be optional. For more notes and examples about this idea, please see the [description of PR 837](https://github.com/google/grr/pull/837).

The way this list-based implementation works is: 

1. sort all the routes (which are represented as lists of strings representing HTTP methods and path components, such as `["GET", "fixed1", "<arg1>"]`) and mark all of them as unvisited.
2. iterate through the routes and for each route that hasn't been visited, consider it a new stem route, then:
    1. start looking to the right of the newly discovered stem route for the route that extends it.
    2. if the extending route is found, mark it as visited and continue the search for the route that extends this newly found one, to its right in the list of routes.
4. after finding the longest route in the group of routes that extend the stem route, extract the required path parameters from the stem route, and the optional ones as the path parameters that appear in the longest route, but not in the stem route.

### Notes
1. Sorting the list of routes insures us that all the extending routes of a route are to its right in the list. This property helps us avoid grouping together groups of routes (e.g. `_prefix_/arg1/arg2`, `_prefix_/arg1/arg2/arg3` and `_prefix_/arg1` in this order would require to "merge" the groups with the stems `_prefix_/arg1/arg2` and `_prefix_/arg1`). An alternative to sorting and using this property is using a disjoint-set forest, but I believe that would make the code harder to read and the time complexity advantage is not extremely important as it doesn't change the overall complexity of the algorithm.

## Time complexity analysis
### Notations:
- N = total number of all the path components of all the routes (even components that overlap with components from other route)
- N' = total number of nodes in the generated trie
- H = the maximum number of components in a route
- R = the number of routes associated with the current router method
- L = the maximum length of a string representing a route

### Trie-based solution
The time complexity of the trie-based solution is:
- O( N = creation of the trie
    - \+ N' = "touching" all the nodes in the trie during the depth traversal
    - \+ R \* H = copying the path params of newly found routes group in lists of required and optional parameters
    - \+ R \* H = arranging the detected routes and their path parameters into `RouteInfo` named tuples (replaced by class instances in the list-based implementation) at the end of `_GetGroupedRoutes`
- )

=> O(N \+ N' \+ R \* H), but N' <= N <= R \* H <= R \* L, therefore **O(R \* L)**.

### Lists-based solution
The time complexity of the lists-based solution is:
- O( R \* logR \* L = lexicographically sorting the routes represented as lists of strings
    - \+ R \* (R \* L) = traversal of the stem routes and their possible extensions together with the checks if the candidate routes extend the stem route
    - \+ R \* H = extracting and separating the path arguments when a group of routes is found
- )

=> O(R \* logR \* L + R^2 \* L + R \* H), but R \* H <= R \* L, therefore **O(R^2 * L)**

### Notes
1. I've presented in the complexity computation only the points of interest in the code that might affect the asymptotic time complexity.
2. I didn't analyze the common parts of code, especially the code that calls the two implementations, as this comparison is strictly of the two implementations of extracting the grouped routes.

## Conclusion
The trie-based solution has a better time complexity, but it also uses an extra O(H) space complexity on stack and is harder to read. Also, the fact that the number of routes associated with a single router method is currently, and also probably in the future, very small, I believe makes the time complexity a small factor in deciding which implementation to use, compared to readability.

Please let me know your suggestions and if you find any mistakes in the algorithm / analysis.

2020-09-08 12:00 UTC, panhania requested changes

2020-09-08 13:23 UTC, alexandrucosminmihai commented on grr/server/grr_response_server/gui/api_plugins/metadata.py
> +  return 0
I made the change. Thank you for your suggestion!

2020-09-08 13:39 UTC, alexandrucosminmihai commented on grr/server/grr_response_server/gui/api_plugins/metadata.py
> +) -> bool:
I added the documentation. I must have missed this function somehow. Thank you!

2020-09-08 13:50 UTC, alexandrucosminmihai commented on grr/server/grr_response_server/gui/api_plugins/metadata.py
> +  if not(longer_route[-1].startswith("<") and longer_route[-1].endswith(">")):
Thank you for pointing this out!

2020-09-08 13:52 UTC, alexandrucosminmihai commented on grr/server/grr_response_server/gui/api_plugins/metadata.py
> +    if comp.startswith("<") and comp.endswith(">"):
Thank you for your suggestion! I created the `_IsPathParameter` function and the code is cleaner now.

2020-09-08 13:54 UTC, alexandrucosminmihai commented on grr/server/grr_response_server/gui/api_plugins/metadata.py
> +from functools import cmp_to_key
I made the change. Thank you!

2020-09-09 08:19 UTC, panhania approved these changes

2020-09-09 08:21 UTC, merged