On query support for time range
google/grr pull request #852
Opened 2020-09-15 08:57 UTC by tsehori

Following a discussion on google/fleetspeak#281, we would like to pass a time range to the `/query` API endpoint rather than a specified `limit`. This way, we can retrieve much more meaningful and more accurate datapoints from Fleetspeak's database.

Note that this PR depends on google/fleetspeak#294, and will work only once google/fleetspeak#294 is merged.

2020-09-15 15:50 UTC, mbushkov requested changes
Looks good! A few minor comments.

2020-09-15 15:50 UTC, mbushkov commented on grr/server/grr_response_server/bin/grrafana.py
> +def _GrafanaTimestampToTimestampObj(
Given that we explicitly test this function in the testing module, I'd suggest not making it module-private (i.e. removing the leading "_").

2020-09-15 15:50 UTC, mbushkov commented on grr/server/grr_response_server/bin/grrafana.py
> +    grafana_time: Text) -> timestamp_pb2.Timestamp:
`Text` was only needed for Python 2->3 migration. Please use `str`.

2020-09-15 15:50 UTC, mbushkov commented on grr/server/grr_response_server/bin/grrafana_test.py
> +  def testGrafanaTimestampToTimestampObj(self):
This is a standalone function that is used by Grrafana HTTP server, but has no direct relation to it. The current class (`GrrafanaTest`) is a set of tests for the HTTP server. I'd put this test in a separate test suite (call it GrafanaTimestampToTimestampObjTest).

2020-09-21 13:01 UTC, max-vogler approved these changes

2020-09-22 08:39 UTC, merged