Added a form in the new UI for Osquery
google/grr pull request #869
Opened 2020-10-16 14:45 UTC by simstoykov

2020-10-16 15:31 UTC, max-vogler requested changes
Please provide a cropped screenshot showing your UI changes.

2020-10-16 15:31 UTC, max-vogler commented on grr/server/grr_response_server/gui/ui/components/flow_args_form/osquery_form.ng.html
> +    <input matInput placeholder="" formControlName="timeoutMillis">
Please limit the values of this input field to numbers.

2020-10-16 15:40 UTC, simstoykov commented
Thanks for the review, that's how it looks: ![Osquery from](https://user-images.githubusercontent.com/35629151/96279190-a3c5cf80-0fd6-11eb-8ac6-d4ce4ff5b159.png)

2020-10-20 13:28 UTC, mbushkov approved these changes

2020-10-20 14:09 UTC, simstoykov commented
@max-vogler Can you PTAL when you have time (could be after tomorrow)

2020-10-20 14:23 UTC, merged