Add a button to the UI for exporting Osquery results to CSV
google/grr pull request #893
Opened 2020-11-26 14:19 UTC by simstoykov

2020-11-26 14:20 UTC, simstoykov commented
Below you can see that the button is not displayed when the flow encountered an error, and it is displayed if it finished successfully with results:
![image](https://user-images.githubusercontent.com/35629151/100361782-e2e63800-2ffa-11eb-84f9-6efce42ab521.png)

2020-11-30 17:20 UTC, max-vogler requested changes

2020-11-30 17:20 UTC, max-vogler commented on grr/server/grr_response_server/gui/ui/components/flow_details/plugins/osquery_details.ts
> +      map(table => table.rows?.length),
`atLeastOneRowAvailable` sounds like a boolean, but the underlying type seems to be number. Please rename if you'd like to keep the type, or convert to a boolean if you'd like to keep the name.

2020-11-30 17:20 UTC, max-vogler commented on grr/server/grr_response_server/gui/ui/components/flow_details/plugins/osquery_details_test.ts
> +    expect(parsedElements.exportCsvButtonText).toBe('Download results as CSV');
Please test that the link contains the correct URL.

2020-11-30 17:20 UTC, max-vogler commented on grr/server/grr_response_server/gui/ui/components/flow_details/plugins/osquery_details.ng.html
> +    <a
Please add the [`download`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a) attribute.

2020-11-30 18:21 UTC, simstoykov commented
@max-vogler PTAL

2020-11-30 18:36 UTC, max-vogler approved these changes

2020-11-30 18:36 UTC, merged